### PR TITLE
Cross MIO Cruise CSV updates to remove vessel designations for all ShipNames

### PR DESCRIPTION
**Pull request by spetillo**
As per discussions during the DMWG on 11/24/20, all MIOs agreed that the vessel designations (R/V, M/V, CCGS, etc.) could be removed from the ShipName in the Cruise CSV. This will make this file more consistent with the shiplist.csv columns, and make the integration of this info into the RDB import & export functionality much smoother.

**Note**: This **PR should not be merged** until dev testing has been completed and PR approved by @oceanzus @steinermg @pauldavidmena to make sure this change doesn't break anything unexpected.

### CODE REVIEW

**Review by oceanzus — COMMENTED** [review]
Could you do me a favor and check for double spaces and comma-space.
Also, what is with the # TO BE DELETED lines?  Not really part of this effort, just stands out as something odd.

**Comment by snwhite** [comment]
The # TO BE DELETED lines are because we are changing/correcting a number of CUIDs (particularly older ones).  We are still in the process of updating all of the deploy CSVs, so we need both CUIDs in this CSV.  Once those updates are completed, we can delete those lines.

**Review by pauldavidmena — APPROVED** [review]
Deployed to dev-03 on 12/1. It looks good to me, but @oceanzus will verify.

**Review by oceanzus — APPROVED** [review]
Looks good on dev03.  No issues found in the UI or data downloads.

**Comment by spetillo** [comment]
@oceanzus I found a few double spaces and one comma-space that wasn't in quotes, all in the Notes column, that have been there since before I touched this file for this PR. Do you need me to remove them?

**Pull request merged**
