### PR TITLE
UUID for the WAVSS-M

### PR DESCRIPTION
**Pull request by cwingard**
Creates a separate UUID for the WAVSS-M sensors that are part of the ADCPT-M instrument in order to preserve the 1:1 mapping of sensors with reference designators.

### CODE REVIEW

**Review by kpolitano — APPROVED** [review]

**Review by snwhite — COMMENTED** [review]
@cwingard This looks good.  I'd suggest putting something in the comment area (right before MIO) that says something about it being the ADCPT-M instrument.

**Comment by cwingard** [comment]
@snwhite Done, added comment and updated PR.

**Review by desiderr — APPROVED** [review]
Looks good.

**Review by snwhite — APPROVED** [review]
@cwingard I like it.  We'll make sure we (@rtravis-whoi ) do it the same way.

**Pull request merged**
