### PR TITLE
+ CE05 312-D13 & 382-R12. Updates E17 cruise return time

### PR DESCRIPTION
**Pull request by s-pearce**
@cwingard can you please review and merge the recent deployment 312-13 and recovery 382-12?  I also updated the arrival time of E17 according to the daily summary from Ed.  I will send the reference documents via email.

Thanks, 
Stuart

### CODE REVIEW

**Review by lstoltz — COMMENTED** [review]
Do you have documents for me to compare against?

**Review by lstoltz — CHANGES_REQUESTED** [review]
EK time I think is incorrect. 13:41 PDT = 20:41 not 18:41

I also could not tell from the config sheet if ADCP Sn: 55980 is on glider 382. Probably my unfamiliarity with the sheet, but if you could confirm that is true I will take your word.

**Comment by s-pearce** [comment]
Okay.  Thanks, good catch on the cruise time. I have updated it and pushed the new commit.

For the ADCP numbers in the deployment csv sheets in AM, they did not want to break their naming convention of 5 digits but the Glider ADCP/DVL serial numbers have 6 digits, so they dropped the leading/6th digit from the serial number.  So on 312's configuration sheet that I sent you, it says DVL 655980 which corresponds to 655980 on 312's deployment csv sheet.  382 was just a recovery, so only the recovery time and cruise ID needs verification, but I am kind of assuming that you meant the ADCP on 312?

**Comment by lstoltz** [comment]
> @lstoltz Okay. Thanks, good catch on the cruise time. I have updated it and pushed the new commit. For the ADCP numbers in the deployment csv sheets in AM, they did not want to break their naming convention of 5 digits but the Glider ADCP/DVL serial numbers have 6 digits, so they dropped the leading/6th digit from the serial number. So on 312's configuration sheet that I sent you, it says DVL 655980 which corresponds to 655980 on 312's deployment csv sheet. 382 was just a recovery, so only the recovery time and cruise ID needs verification, but I am kind of assuming that you meant the ADCP on 312?

Yes I see the SN now. Thanks for the info. I am satisfied with the deployment and recoveries for the gliders, I would still like to verify calibration coefficients for the cal csv's you are uploading in this PR.

**Review by lstoltz — APPROVED** [review]
Looks good

**Pull request merged**
