### PR TITLE
Deploy CSV column addition to support import of these CSVs into RDB

### PR DESCRIPTION
**Pull request by spetillo**
This change adds 2 columns to the end of each row in all Deployment CSVs, and also adds the appropriate headers (`electrical.uid` and `assembly_template_revision`) to these columns in the first row of each affected file.

Starting in early March, I will work with each MIO to populate these two new columns, which will support the auto-import of the Deployment metadata into Roundabout.

I have pre-tested an example file with @oceanzus to make sure this change will not break anything in the CI system.

I also used two `sed` commands to make all of these changes automatically and consistently so that I couldn't fat-finger anything. As such, **reviewers should only need to review the changes for one of their Deployment files, and can assume that the rest follow suit** (of course, you _can_ review them all if you _really_ want to).

**I will wait for one reviewer approval from each MIO and @oceanzus before merging.**

(If there's someone else from your MIO that should be on the reviewer list, let me know.)

### CODE REVIEW

**Comment by spetillo** [comment]
Looks like this change requires an update to the [test_deploy.py](https://github.com/oceanobservatories/asset-management/blob/master/test/unit/test_deploy.py) code behind the nosetests to handle the extra columns... I'm working on an appropriate fix.

**Comment by spetillo** [comment]
Looks like I didn't actually need to change the the `test_deploy.csv` after all, though now that I look at that code, I wonder if I should add my new fields to `optional_ids` anyway? @steinermg

**Review by snwhite — APPROVED** [review]
I looked over a few different types of Coastal Pioneer and Global platforms, and they all look fine to me.

**Review by cwingard — APPROVED** [review]

**Review by desiderr — APPROVED** [review]
Checked Endurance deploy.csv files excepting gliders.

**Review by s-pearce — APPROVED** [review]
I would have preferred that the 2 added columns precede the notes column (of variable length) to not disrupt the quickly viewable data columns.  But I also don't think that is worth requesting that change, for an already less-than-ideal system anyway.
For which reason, I do appreciate the step forward to getting this into a database.

Anyway, endurance gliders indeed have the new columns and appropriate commas.

**Review by wruef — APPROVED** [review]

**Pull request merged**
