### PR TITLE
Cspp deployments 

### PR DESCRIPTION
**Pull request by aguirremar**
added deployments CE01 D24, CE02 D36, CE06 D18, 
closed deployments CE01 D23, CE02 D35, CE06 D18, CE07 D16
All supporting documents are in Alfresco for review.

### CODE REVIEW

**Review by cwingard — APPROVED** [review]
Pulled supporting docs from Alfresco and cross-compared. Looks good here.

**Comment by aguirremar** [comment]
[like]  Aguirre Nunes, Mariana reacted to your message:
________________________________

**Review by s-pearce — APPROVED** [review]
@aguirremar , I am approving this pull request, BUT I have 2 direct complaints, and several nit picky complaints or suggestions that are indirectly related.
--direct--
1. the direct complaint is that I could not evaluate the recovery time entered for deployment 18 in deployment/CE06ISSP_Deploy.csv because the Deployment worksheet on Alfresco did not have a recovery time entered and there is no accompanying small boat quick look report.  I still approved it, because I trust you got it right, but could not cross check.

2. I noted there were several cases where the instrument serial numbers given had last calibration files in AM that are older than 2 years (out of date).  If you have updated calibration dates for them newer than what is in AM, you should add them.
CE01: PARAD-J 365
CE02: FLORT-J 1207; PARAD-J504; SPIKR-J 281
CE06: OPTAA-J 138
 - Also not sure why there isn't a CTDPF-J or VELPT-J directories in calibrations.

--indirect--
3. I highly suggest that in the Deployment worksheet on the configuration tab, you add a column for last calibration date.  I suggested this to Linus too, but he never added it.  It would be much better for visibility for if calibrations are within spec.
4. On Alfresco, The recovery time in the worksheet for CE02 deployment 36, is formatted as a float number instead of a date time.  I would change this, but I am not the owner of the document and so cannot change it on Alfresco (this may be a task for Jon).
5. In the Quick look report for EK20240502 in the deployment table, the time does not match the Deployment worksheet.
6. For the cruise added (EK2024085), the times do not match the cruise quick look report log, only so much as the minutes are not added in the CruiseInformation.csv.  I won't ask you to change it and it doesn't matter too much, but I usually am correct to the minute when I add a cruise.
7. I encourage you to add recovery cruise ID's (and maybe even personnel) to AM deployment csv files for future recoveries.  I think it is generally useful metadata.
8. Lastly, I think in platform_bulk_load-AssetRecord.csv, the Manufacturer should be listed as WETLabs instead of WHOI.  Not sure why it is listed that way.  If you care to change this though, it should be at a future time and not part of this pull request.

Sorry for my nit picky review, but just stating my opinion on things.
-Stuart

**Comment by s-pearce** [comment]
Actually scratch direct complaint number 1.  I was using the older working copy and it looks like it was last modified today on Alfresco.

**Comment by aguirremar** [comment]
Hey Stuart,

Sorry it took me forever to reply. It is indeed a lot of comments hehe
Keep in mind this was my first real Asset Management "action", I'm just starting on this part, so please be patient :)
I'll copy your comments and reply below them in blue.


  1.
the direct complaint is that I could not evaluate the recovery time entered for deployment 18 in deployment/CE06ISSP_Deploy.csv because the Deployment worksheet on Alfresco did not have a recovery time entered and there is no accompanying small boat quick look report. I still approved it, because I trust you got it right, but could not cross check.
        *
I see you found this. I believe I had it open to do recovery editing before doing the AM things, and didn't actually close and save the new version, but I noticed it while I was downloading the spreadsheets to share with you. Sorry about that.
  2.
I noted there were several cases where the instrument serial numbers given had last calibration files in AM that are older than 2 years (out of date). If you have updated calibration dates for them newer than what is in AM, you should add them.
CE01: PARAD-J 365
CE02: FLORT-J 1207; PARAD-J504; SPIKR-J 281
CE06: OPTAA-J 138
        *
I was not the one taking care of files in GitHub or anywhere else except Vault. I might be the one taking care of it soon. However, some calibrations are indeed pretty old (I found instruments dating back to 2018).

  *
Also not sure why there isn't a CTDPF-J or VELPT-J directories in calibrations.
        *
That it probably because they virtually never go to the vendor.

--indirect--
3. I highly suggest that in the Deployment worksheet on the configuration tab, you add a column for last calibration date. I suggested this to Linus too, but he never added it. It would be much better for visibility for if calibrations are within spec.
      Do you need the calibrations to check the deployment details, or is it for something else you're suggesting?
4. On Alfresco, The recovery time in the worksheet for CE02 deployment 36, is formatted as a float number instead of a date time. I would change this, but I am not the owner of the document and so cannot change it on Alfresco (this may be a task for Jon).
      I've gone through many issues with this spreadsheet and the data format there, we've come to the conclusion that we might be having Excel version issues; because I keep changing the date format but it doesn't work. But  hopefully this spreadsheet is going to get extinct soon, because we all dislike it for a variety of reasons, so this problem might go away!
5. In the Quick look report for EK20240502 in the deployment table, the time does not match the Deployment worksheet.
      My bad, probably a typo. Thanks for pointing that out!
6. For the cruise added (EK2024085), the times do not match the cruise quick look report log, only so much as the minutes are not added in the CruiseInformation.csv. I won't ask you to change it and it doesn't matter too much, but I usually am correct to the minute when I add a cruise.
      Do you mean the cruise EK20240815? Is the deployment time supposed to be in the CruiseInformation.csv as well? I only added the start and end time of the cruise (2024-08-15,15:00 / 18:00) - Those are from Jon's notes, he had it as 00min so that's how I added it, but I get it, I usually add the exact minutes as well hehe
7. I encourage you to add recovery cruise ID's (and maybe even personnel) to AM deployment csv files for future recoveries. I think it is generally useful metadata.
      The recovery cruise IDs are also on the plan, not sure when that is going to happen though.. we do have personnel added to the CSPP spreadsheet, it just doesn't go to AM...
8. Lastly, I think in platform_bulk_load-AssetRecord.csv, the Manufacturer should be listed as WETLabs instead of WHOI. Not sure why it is listed that way. If you care to change this though, it should be at a future time and not part of this pull request.
      Yeah I had the same question.. not sure why it's like that; also not sure how much "jurisdiction" I have to make that big of a change yet.



Anyway, I honestly appreciate your comments. Don't hesitate to send feedback anytime; this is something new for me and I don't expect to do it correctly in the first few iterations. I also might need your help with Asset Management at some point hehe

Thanks,

Mari

________________________________

**Pull request merged**
