### PR TITLE
Move from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by rgov**
On November 2, 2020, Travis CI [ended their free support for open source projects](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). Open source projects now receive a one-time allocation of about 1,000 build-minutes.

This pull request moves the Travis CI configuration to GitHub Actions, which is a free offering built into GitHub. You can see an example of it here:

https://github.com/rgov/asset-management/runs/1682544745?check_suite_focus=true

The configuration is virtually the same, installing Python 2.7 via `conda` and then running `nosetests`.

However, I did not port over the Slack integration because I do not know what messages you would like sent to Slack. You could also consider using the [GitHub App for Slack](https://slack.github.com) rather than building it into the CI workflow.

### CODE REVIEW

**Comment by snwhite** [comment]
This needs to be a Programmatic decision coming from Jeff Glatstein.

**Comment by spetillo** [comment]
It sounds like this would be a reasonable changeover, since Travis CI is going to start limiting us and its integration with our PR workflow was already not working consistently (sometimes tests were run when a PR was made, but sometimes they were only run when the PR was merged). I _hope_ this github workflow integration will be much more seamlessly and reliably integrated.

As @snwhite mentioned, @JGlatstein would need to give the final OK from a programmatic standpoint. I'm reserving my approval until we get word on that, but otherwise the tests.yml implementation looks fine and appears to run the tests fine.

I can't speak to the need for the slack integration, so I'd look to @pauldavidmena and @JGlatstein for input there...

@rgov :
1. Could this be configured such that the Github Actions tests are also run every time a PR is _updated_ (not just when the PR is created)? 
2. Will this also re-run the tests upon PR merge, or does the "push" run condition cover that?

**Comment by pauldavidmena** [comment]
I'm not seeing the same Slack integration in tests.yml that I find in .travis.yml. @rgov - is it easy enough to port https://github.com/oceanobservatories/asset-management/blob/master/.travis.yml#L6-L7 over?

**Comment by rgov** [comment]
@spetillo 

> Could this be configured such that the Github Actions tests are also run every time a PR is updated (not just when the PR is created)?

Yes, GitHub does this already; every time you change the pull request (such as by pushing a commit to the PR branch), it will be re-run. [Docs](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request).

> Will this also re-run the tests upon PR merge, or does the "push" run condition cover that?

Yes, I believe that a [`push`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push) event is generated when you merge a pull request. However I think the build result should be the same as the last result of the PR (since they are running the same workflow on the same repository state).

@pauldavidmena

See last paragraph of PR description -- I don't know what notifications you would like sent to Slack; I'm not sure what Travis sends to you now. It is possible to send notifications to Slack from CI, it is also possible to connect Slack to GitHub without modifying the CI config.

**Comment by spetillo** [comment]
More questions...

@JGlatstein @pauldavidmena 
Do we want this to run the nosetests for PRs and commits into the master branch only, or into all branches? (I think the default is master only, based on what the docs say, but @rgov back me up here.)

Thinking aloud, I'm also wondering if this will trigger nosetests on all of our PRs _within_ our forks, which would actually be good, but is not essential.

**Comment by rgov** [comment]
I think it covers any commit pushed to any branch. For instance, I did this work on the `rzg/github-ci` branch of my repo, which is not the main branch, and it did check it.

When you fork the repo, it should carry the CI workflow with it, but if you have secrets (such as Slack integration credentials) attached to the upstream repo, the forks do not have access to those secrets.

Of course if you feel the behavior needs to be tweaked after you have tried it for a few rounds of PRs, it is very flexible.

**Comment by spetillo** [comment]
@rgov  Can you add a "status check" on this GitHub Action, so we can set `master` branch protections such that a PR into `master` cannot be merged if the `nosetests` in this GitHub Action don't pass?

I think this is do-able by enabling the "Require status checks to pass before merging" branch protection (which @pauldavidmena or I can do easily) and then [setting up a status check](https://docs.github.com/en/rest/reference/repos#statuses). I just don't have time to dig into properly setting up the status check component myself....

**Comment by rgov** [comment]
@spetillo I investigated this and it doesn't seem like there's anything additional that needs to be done. GitHub automatically identifies workflows as "status checks."

Here's what it looked like on my test repo:

image

And when I made that configuration change, here is what happens when I have a pull request that is failing:

image

**Comment by spetillo** [comment]
@rgov Perfect, thanks!

**Comment by spetillo** [comment]
As per DMWG discussion today, there were no objections to moving forward with this change. I am approving, but will leave it to @pauldavidmena to merge this after the upcoming `asset-management` release is complete.

After merge, we need to remember to activate the `master` branch protection, as per the comment above.

**Review by spetillo — APPROVED** [review]

**Review by spetillo — CHANGES_REQUESTED** [review]
@rgov our [README.md](https://github.com/oceanobservatories/asset-management/blob/master/README.md) shows the current build status at the top. Can you also update that to whatever the new URL will be to display the test result status from this Github Action?

**Comment by rgov** [comment]
Ok, I fixed the badge. It should look like this:

Build Status

and your old one looks like

Build Status

**Review by spetillo — APPROVED** [review]
Great. Thanks for the updated badge

**Comment by pauldavidmena** [comment]
I'm not a reviewer on this PR (nor do I need to be), but I heartily approve! Thank you @rgov for the input.

**Comment by spetillo** [comment]
@JGlatstein Am I good to merge this?

**Comment by pauldavidmena** [comment]
Good morning, @spetillo - I spoke to @JGlatstein this morning, and he thought the merge was completed. I think it's safe to proceed if you're okay with that.

**Pull request merged**
