### PR TITLE
ACS 139 cal info

### PR DESCRIPTION
**Pull request by lstoltz**

### CODE REVIEW

**Comment by lstoltz** [comment]
I think I sent this to get checked a while ago. Please merge when you get a chance. Thanks

**Comment by s-pearce** [comment]
> I think I sent this to get checked a while ago. Please merge when you get a chance. Thanks

Strange, I just checked my email and I have nothing back from Nov 2 asking me for a review.  The last email I have from Github from Asset-Management is October 20th.  Sorry I would have done it otherwise.

**Comment by lstoltz** [comment]
@s-pearce I just added you, so it makes sense to not be in your email. I was casually shaming @cwingard

**Review by s-pearce — APPROVED** [review]
I can't check them all, but skimming the edges (first 7 ish of the top left, and last 7ish of the bottom right) for each array looks right and the first several and last several of the vectors looks right.

**Review by s-pearce — APPROVED** [review]
more approval after addition of deployment sheets, cal sheet for nutnr and bulk ass. load

**Pull request merged**
