### PR TITLE
Updates to Endurance calibration file generation scripts

### PR DESCRIPTION
**Pull request by desiderr**

### CODE REVIEW

**Review by cwingard — CHANGES_REQUESTED** [review]
I'm seeing a number of `^M` characters in the scripts, especially after the `...` characters where you continue the code on the next line. Those break the functions in Linux. Can you double-check/run dos2unix on the m-files?

**Comment by desiderr** [comment]
Ran dos2unix on all files, this seems to have worked.

**Review by kpolitano — APPROVED** [review]
All README files look good, however, PRESF file does not explain what the compareFiles function is for. Because you explained it during the meeting I think we all know what it is for, but an outside person using it in the future might not immediately know. Maybe an explanatory sentence would be good.

**Comment by desiderr** [comment]
I may have skipped explanations in the readme files for some of the other 'extra' programs, too.  I always have documentation inside the code itself - inside that function, the documentation is:

function comparePRESFcsvCalfiles(file1, file2)
%.. desiderio 24-feb-2023 accepts two calling arguments each naming an OOI
%..                       csv calfile from the same SBE26P (PRESF) sensor
%..                       and compares their cal coeffs; these are
%..                       for pressure and usually (never?) change,
%..                       except for a particular OFFSET
%

Is that sufficient? I can always paste that into the presf readme.

**Review by cwingard — APPROVED** [review]

**Comment by mjozirbel** [comment]
nutnrCalFileCheckFunction.m had a reference to a local machine's file structure, otherwise everything worked well.

**Review by mjozirbel — APPROVED** [review]
Reviewed with RAD, removed local file reference (line 261) in nutnrCalFileCheckFunction.m
All good.

**Pull request merged**
