### PR TITLE
updated for ce02 cspp turn

### PR DESCRIPTION
**Pull request by lstoltz**

### CODE REVIEW

**Comment by lstoltz** [comment]
Not sure who tag since everyone is on vaca. I will email config sheets to you folks

**Review by s-pearce — APPROVED** [review]
I @s-pearce hereby approve of these record additions.

@lstoltz I would encourage starting to add recovery cruise IDs too, although not necessary from a AM verification step.

**Comment by s-pearce** [comment]
@lstoltz I don't have any documentation to verify the NUTNR cals, but I verified that there were 256 in each array parameter at least and the scalars look reasonable.  I think these are generated by parsing scripts anyway as I understand it.  So approving and merging anyway.

**Review by desiderr — COMMENTED** [review]
I checked the NUTNR csv cal coeffs against those in the corresponding instrument calfile, they match. I've also checked the other aspects of the pull request which I approve.

**Pull request merged**
